### ISSUE TITLE
Sugiyama layout

### ISSUE THREAD

**Issue by hpoit** [JuliaGraphs/NetworkLayout.jl#10]
Hey @abhijithanilkumar. That's nice, thanks for the distinction. I want to add the Sugiyama to NetworkLayout. Let me see what I can find on Github that's maybe already in Julia or well written. [#13](https://github.com/abhijithanilkumar/NetworkViz.jl/issues/13#issuecomment-279237006) @tawheeler

**Comment by hpoit** [comment]
I need to evaluate which 4 steps make more sense-- [Ithaka Digraph's](https://github.com/beckchr/ithaka-digraph/tree/master/src/main/java/de/odysseus/ithaka/digraph/layout/sugiyama) or [Seok Hee Hong's](http://www.cs.usyd.edu.au/~shhong/fab.pdf).

**Comment by abhijithanilkumar** [comment]
I think [this](https://github.com/IainNZ/GraphLayout.jl/blob/master/src/tree.jl) is what you are searching for.

**Comment by hpoit** [comment]
Awesome! @tawheeler, acceptable?

**Comment by tawheeler** [comment]
Go for it
