### ISSUE TITLE
Duplicate definitions for Point

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/NetworkLayout.jl#12]
```
INFO: Precompiling module GeometryTypes.
WARNING: both FixedSizeArrays and GeometryTypes export "Point"; uses of it in module Stress must be qualified
ERROR: LoadError: LoadError: LoadError: UndefVarError: Point not defined
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:539
 [2] include(::String) at ./sysimg.jl:14
 [3] include_from_node1(::String) at ./loading.jl:539
 [4] eval(::Module, ::Any) at ./boot.jl:235
 [5] require(::Symbol) at ./loading.jl:453
 [6] include_from_node1(::String) at ./loading.jl:539
 [7] eval(::Module, ::Any) at ./boot.jl:235
 [8] require(::Symbol) at ./loading.jl:453
while loading /Users/bromberger1/.julia/v0.6/NetworkLayout/src/stress.jl, in expression starting on line 79
while loading /Users/bromberger1/.julia/v0.6/NetworkLayout/src/NetworkLayout.jl, in expression starting on line 6
while loading /Users/bromberger1/.julia/v0.6/PlotRecipes/src/PlotRecipes.jl, in expression starting on line 8
```

This maybe isn't something that we should be fixing here (but we could work around it by explicitly stating which one we use), but this is happening when trying to compile PlotRecipes with latest masters of NetworkLayout, GeometryTypes, and PlotRecipes.

**Comment by SimonDanisch** [comment]
This needs fixing here and is a side effect of you using GeometryTypes master which relies on StaticArrays, while `stress.jl` still relies on FixedSizeArrays...

**Comment by SimonDanisch** [comment]
should be as simple as replacing `FixedSizeArray` with `StaticArrays` and `FixedArray` with `StaticArray`... or so ;)

**Comment by sbromberger** [comment]
Hah. I'm gonna leave this for @abhijithanilkumar :)

**Comment by mkborregaard** [comment]
@sbromberger once this is fixed, could you ping me if there are still issues with PlotRecipes? I will make it a priority to get this done.

**Comment by sbromberger** [comment]
@mkborregaard sure will. Thanks for your help on this.

For the record, I don't understand the vis code at all - I'm just a user of this eager to resume visualizing my graphs :)

**Comment by mkborregaard** [comment]
bump! :-)

**Comment by sbromberger** [comment]
@mkborregaard It's still not working as of this evening (via master). Should I be doing something in particular?

**Comment by mkborregaard** [comment]
I'd guess it's just a question of replacing FixedSizeArrays with StaticArrays calls, like @SimonDanisch said?

**Comment by sbromberger** [comment]
Working on it.

**Comment by abhijithanilkumar** [comment]
Sorry for the delay. I'll fix this ASAP. @sbromberger @mkborregaard

**Comment by sbromberger** [comment]
@abhijithanilkumar I'm almost done. Give me 2 days?

**Comment by abhijithanilkumar** [comment]
@sbromberger Sure. I don't mind taking over if you're already busy with something else.

**Comment by sbromberger** [comment]
@abhijithanilkumar be my guest, then, please! I'm stuck on a few things and you can probably hammer this out much more quickly.

**Comment by mkborregaard** [comment]
Hi @abhijithanilkumar what's the status on this? :-)
