### ISSUE TITLE
tag a new release?

### ISSUE THREAD

**Issue by daschw** [JuliaGraphs/NetworkLayout.jl#15]
The current release is not working for me on julia 0.6:
```julia
julia> versioninfo()
Julia Version 0.6.0
Commit 903644385b* (2017-06-19 13:05 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
  WORD_SIZE: 64
  BLAS: libblas
  LAPACK: liblapack
  LIBM: libm
  LLVM: libLLVM-4.0.0 (ORCJIT, skylake)

julia> Pkg.status("NetworkLayout")
 - NetworkLayout                 0.0.1

julia> using NetworkLayout # errors
WARNING: both FixedSizeArrays and GeometryTypes export "Point"; uses of it in module Stress must be qualified
ERROR: LoadError: LoadError: UndefVarError: Point not defined
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:569
 [2] macro expansion at ./REPL.jl:97 [inlined]
 [3] (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:73
while loading /home/dani/.julia/v0.6/NetworkLayout/src/stress.jl, in expression starting on line 79
while loading /home/dani/.julia/v0.6/NetworkLayout/src/NetworkLayout.jl, in expression starting on line 6

julia> Pkg.checkout("NetworkLayout")
INFO: Checking out NetworkLayout master...
INFO: Pulling NetworkLayout latest master...
INFO: Removing FixedSizeArrays v0.2.5

julia> using NetworkLayout # works

julia>
```

**Comment by sbromberger** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/10485

**Comment by daschw** [comment]
Great, thanks!

**Comment by MikeB2012** [comment]
Sorry, same problem but I don't understand this response.  Completely new to Julia.

**Comment by sbromberger** [comment]
@mikeB2012 you should be able to fix it now by simply doing `Pkg.update()`.

**Comment by MikeB2012** [comment]
Thank you for the quick response.  When I do Pkg.update():
julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating NetworkLayout master...
INFO: Computing changes...
INFO: No packages to install, update or remove
Versioning info is:
julia> Pkg.status("NetworkLayout")
 - NetworkLayout                 0.0.1+             master
 - LightGraphs                   0.9.5
Shouldn't that read '0.1.0'?  I tried removing and adding again and running the toy example:
  using LightGraphs
  using NetworkLayout:SFDP
  g = WheelGraph(10)
  a = adjacency_matrix(g) # generates a sparse adjacency matrix
  network = layout(a,Point2f0,tol=0.1,C=1,K=1,iterations=10) # generate 2D layout
The result is an error: 
  ERROR: UndefVarError: layout not defined
Any thoughts or recommendations are appreciated.

**Comment by sbromberger** [comment]
Until https://github.com/JuliaLang/METADATA.jl/pull/10485 is merged the best you can do is
```
Pkg.checkout("NetworkLayout")
```
which should work.

**Comment by MikeB2012** [comment]
Again, thanks for the quick reply.  Pkg.checkout() didn't change the situation, I still see the same error.  On the plus side, I'm not seeing any error other than the one I mentioned above.

**Comment by abhijithanilkumar** [comment]
Can you please post here, the error you're getting now?

**Comment by MikeB2012** [comment]
It remains the same:  ERROR: UndefVarError: layout not defined.

**Comment by sbromberger** [comment]
The reason is that you're only importing one thing from NetworkLayout:
```
using NetworkLayout:SFDP
```
If you change that to `using NetworkLayout`, you will import all functions, including `layout`.

**Comment by MikeB2012** [comment]
I tried that but it made no difference.  BTW, I'll move the question to the visualization discourse.  Cheers.

**Comment by abhijithanilkumar** [comment]
@MikeB2012 Can you try `SFDP.layout` ? I think it is probably an error in the README. Sorry about that.

**Comment by sbromberger** [comment]
I can reproduce the issue.

**Comment by abhijithanilkumar** [comment]
`layout` is not exported since every algorithm has a layout function. `<Algo>.layout` should work.

**Comment by MikeB2012** [comment]
When try SFDP.layout the error (using IJulia) is:

UndefVarError: Point2f0 not defined
Stacktrace:
 [1] include_string(::String, ::String) at .\loading.jl:515

**Comment by abhijithanilkumar** [comment]
To use Point2f0, you need to import GeometryTypes.

**Comment by MikeB2012** [comment]
Okay, that sort of did it.  I get no errors and the following output.  I did expect a graphic though but didn't get one either from CLI or IJulia.

10-element Array{GeometryTypes.Point{2,Float32},1}:
 Float32[-0.989168, -0.693321]
 Float32[-1.65888, -0.261564] 
 Float32[-2.00881, 0.175499]  
 Float32[-2.2372, -1.58388]   
 Float32[-1.63838, -1.70653]  
 Float32[-0.686665, -1.72838] 
 Float32[0.048257, -1.38027]  
 Float32[0.546967, -0.714966] 
 Float32[0.167115, -0.221661] 
 Float32[-0.726439, 0.268255]

**Comment by abhijithanilkumar** [comment]
You will not get a graphic output by using `NetworkLayout` alone. It'll generate the co-ordinates for you. You'll have to use a visualization package like GLVisualize, GraphLayout, NetworkViz, etc. to get a graphic output.

**Comment by MikeB2012** [comment]
Ah ... got it.  Thank you for the time and patience!

**Comment by sbromberger** [comment]
@MikeB2012 - if you're on 0.6 and running latest versions of everything, GraphPlot.jl might be what you want.
