### ISSUE TITLE
Julia 1.1

### ISSUE THREAD

**Issue by BastianMoya** [JuliaGraphs/NetworkLayout.jl#18]
is it work with Julia 1.1? 
I have the next message when I try to do an example. 

UndefVarError: layout not defined
top-level scope at none:0

**Comment by mantzaris** [comment]
the examples of NetworkLayout.jl are not working:

```
using NetworkLayout.SFDP
using NetworkLayout.Spring
using NetworkLayout.Stress
using NetworkLayout.Buchheim
using NetworkLayout.Spectral
using NetworkLayout.Shell
using NetworkLayout.Circular
using LightGraphs
using GeometryTypes
using DelimitedFiles: readdlm
using SparseArrays: sparse
using Test
using LightGraphs
using NetworkLayout:SFDP
g = WheelGraph(10)
a = adjacency_matrix(g) # generates a sparse adjacency matrix
network = layout(a,Point2f0,tol=0.1,C=1,K=1,iterations=10) # generate 2D layout
```
 I keep getting an error:
```
**UndefVarError: layout not defined
Stacktrace:
 [1] top-level scope at In[38]:5**
```
I've tried this on 2 different computers

**Comment by sbromberger** [comment]
Use one of the `layout` functions defined in whatever layout submodule you want:
```
using LightGraphs
using NetworkLayout
using NetworkLayout:Spring

g = WheelGraph(10)
a = adjacency_matrix(g)
network = Spring.layout(a)
```

**Comment by mantzaris** [comment]
The documented function allows for the *iterations* to be provided as a parameter, and therefore how does the `Spring.layout` handle this value? Does it increase the iterations by default till there is a 'convergence'?

**Comment by abhijithanilkumar** [comment]
No, it does not run till convergence. It stops when it hits maximum iterations.
