### ISSUE TITLE
Admin rights

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaGraphs/NetworkLayout.jl#26]
@sbromberger I somehow seem to have lost admin rights to this repository, even though I'm the main author.
Can you enable those please? Or should I move the package?

**Comment by sbromberger** [comment]
Sure. Dunno why that happened. I haven't made any changes. Give me a few mins to check it out.

**Comment by sbromberger** [comment]
Can you check now? Thanks.

**Comment by SimonDanisch** [comment]
Thanks for looking at it!
But I still don't have the settings tab:
![image](https://user-images.githubusercontent.com/1010467/118404902-374aa600-b675-11eb-94c5-c14a44e0bc67.png)

**Comment by sbromberger** [comment]
Oh, crap. Wrong simon!!! sorry. One sec.

**Comment by sbromberger** [comment]
ok. try now?

**Comment by SimonDanisch** [comment]
Thank you, that worked :)
