### ISSUE TITLE
Renaming LightGraphs to Graphs

### ISSUE THREAD

**Issue by storopoli** [JuliaGraphs/NetworkLayout.jl#42]
In light of [recent moves towards `Graphs.jl`](https://discourse.julialang.org/t/lightgraphs-jl-transition/69526), I think that a simple renaming of `LightGraphs` to `Graphs` might make NetworkLayout compatible with the new `Graphs.jl`.

**Comment by hexaeder** [comment]
yeah I'll tag GraphMakie 0.3 soon which will exclusively support Graphs.jl. For GraphMakie it is not possible to support both at the same time
