### ISSUE TITLE
Unable to draw graphs drawn in Docs. No Method matching Layout

### ISSUE THREAD

**Issue by atiyabzafar** [JuliaGraphs/NetworkLayout.jl#49]
I am unable to plot the networks even shown in the Docs. I have used this library successfully before. And I am able to run using Pluto notebook, but there seems to be a dependency issue in my main julia installed. As it is not drawing in REPL and jupyter.

Error:
`MethodError: no method matching layout(::Spring{2, Float32}, ::SimpleGraph{Int64})
Closest candidates are:
  layout(::NetworkLayout.IterativeLayout, ::AbstractMatrix) at C:\Users\atiya\.julia\packages\NetworkLayout\TxHy6\src\NetworkLayout.jl:75
  layout(::NetworkLayout.AbstractLayout, ::LightGraphs.AbstractGraph) at C:\Users\atiya\.julia\packages\NetworkLayout\TxHy6\src\NetworkLayout.jl:90`

I can see that it is trying to look for LightGraphs. My understanding is that it was moved from lightGraphs to Graphs.

Compiling Pkg.status() gives me following 
`
  [6e4b80f9] BenchmarkTools v1.3.1
  [0f109fa4] BifurcationKit v0.1.11
  [336ed68f] CSV v0.10.4
  [159f3aea] Cairo v1.0.5
  [13f3f980] CairoMakie v0.6.4
  [a81c6b42] Compose v0.9.3
  [8f4d0f93] Conda v1.7.0
  [a93c6f00] DataFrames v1.3.3
  [0c46a032] DifferentialEquations v7.1.0
  [e9467ef8] GLMakie v0.4.5
  [1ecd5474] GraphMakie v0.2.3
  [a2cc645c] GraphPlot v0.5.0
  [86223c79] Graphs v1.6.0
  [7073ff75] IJulia v1.23.3
  [0f8b85d8] JSON3 v1.9.4
  [b964fa9f] LaTeXStrings v1.3.0
  [46757867] NetworkLayout v0.4.0
  [f0f68f2c] PlotlyJS v0.18.8
  [91a5bcdd] Plots v1.27.5
  [c3e4b0f8] Pluto v0.19.0
  [438e738f] PyCall v1.93.1
  [0f1e0344] WebIO v0.8.17
  [d6f4376e] Markdown
`

What seems to be the issue here? and how can i resolve it? I do not want to start from a fresh install. Or remove a lot of my packages. I tried to force install the latest version but Pkg threw up some dependency issues.

**Comment by hexaeder** [comment]
It seems like you're trying to plot a graph object from `Graphs.jl` but both `NetworkLayout.jl` and `GraphMakie.jl` are both on versions prior to the `Graphs.jl` transition. So you either have to update your packages (networklayout to at least 0.4.2 and GraphMakie to at least 0.3) or use `LightGraphs.jl` objects to maintain compatibility.

**Comment by atiyabzafar** [comment]
Yeah, I understood that much. 
>to at least 0.4.2 

So I tried to update my package to 0.4.4 directly. But it showed a dependency error. And was not letting me update it. I will try once more once I am at the machine and get back here. Thanks.

And yeah I learned this lesson quite late (when I started working in julia) by then my main environment was already a mess. And I am just being lazy to clean up the main environment. My other machine is in a better shape and is thus not showing this problem.

**Comment by atiyabzafar** [comment]
Updating worked!
Thanks for the help. My guess is Force updating package using Pkg.jl is not able to resolve the dependecies for large environments. `] up` did resolve it and did the required updates.
You can close this issue now. :)

**Comment by hexaeder** [comment]
well, if you try to force `] pin NetworkLayout@4.4` it will try to update only this package. Everything else *has* to stay on the old version. A general `] up` will update all the packages within the compat bounds (for example Makie needs to update so GraphMakie can update and so forth)
