### ISSUE TITLE
how to take up whole plot space 

### ISSUE THREAD

**Issue by zvnkk** [JuliaGraphs/NetworkLayout.jl#61]
![image](https://github.com/JuliaGraphs/NetworkLayout.jl/assets/143273920/09c67c32-c56a-47bf-8531-7f23fec5bb3a)
whenever i graphplot(..., size=(600,200)) the outcome is upper image.
however i could not find any parameter of the graphplot that takes up whole space of the plot. 
please help

**Comment by hexaeder** [comment]
Please provide an MWE. Without executable code and a list of packages it is hard to help. Regardless of that: `NetworkLayout.jl` just takes a graph and assigns a coordinate to every node. This is totally unrelated to the described problem of spreading those data positions across an image and specifying final size of that image. For example: both axes in this figure show data within the range (0,10) even though one of them is much wider.
<img width="502" alt="grafik" src="https://github.com/JuliaGraphs/NetworkLayout.jl/assets/35867212/2a6b6d12-d0a0-4ff5-9c0a-cffdc5ffa939">

In case you're using [`GraphMakie.jl`](https://github.com/MakieOrg/GraphMakie.jl) the way to resize a figure is either
```julia
graphplot(g; figure=(;resolution=(1000,300)))
```
or slightly more verbose
```julia
fig = Figure(; resolution=(1000, 300))
ax = Axis(fig[1,1])
graphplot!(ax, g)
```

If your using [`GraphRecipes.jl`](https://github.com/JuliaPlots/GraphRecipes.jl) please check [their docs](https://docs.juliaplots.org/stable/GraphRecipes/introduction/) and also the [docs of `Plots.jl`](https://docs.juliaplots.org/stable/)
